stages:
  - build
  - deploy

build:
  stage: build
  image: docker:23.0.1
  services:
    - docker:23.0.1-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build
      --build-arg CI_COMMIT_SHA="$CI_COMMIT_SHA"
      --file ./Dockerfile
      --tag $IMAGE_TAG .
    - docker push $IMAGE_TAG
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

.deploy:
  stage: deploy
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  image:
    name: bitnami/kubectl:1.26.4
    entrypoint: ['']
  before_script:
    - kubectl config use-context "$KUBE_CONTEXT"
  script:
    - cat k8s/deployment.yaml |
      sed -e "s#@@IMAGE_TAG@@#${IMAGE_TAG}#g" |
      sed -e "s#@@NAMESPACE@@#${NAMESPACE}#g" |
      kubectl apply -f -

deploy:
  extends: .deploy
  variables:
    NAMESPACE: dev-interopdata-demo
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy-prod:
  extends: .deploy
  variables:
    NAMESPACE: com-interopdata-demo
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  when: manual