kind: Deployment
apiVersion: apps/v1
metadata:
  name: demo
  namespace: dev-interopdata-demo
  labels:
    app: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: gitlab-registry-config
      containers:
        - name: demo
          image: "@@IMAGE_TAG@@"
          ports:
            - containerPort: 3000
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 3
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: demo-env
                  key: DATABASE_URL
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: demo-env
                  key: SESSION_SECRET
            - name: INTEROPDATA_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: demo-env
                  key: INTEROPDATA_SECRET_KEY
            - name: INTEROPDATA_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: demo-env
                  key: INTEROPDATA_WEBHOOK_SECRET